# Generated by Django 5.2.4 on 2025-08-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
